# version: '3.8'  # Có thể xóa dòng này để tránh warning
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: laravel_app
#     restart: unless-stopped
#     working_dir: /var/www/
#     volumes:
#       - ./:/var/www
#     networks:
#       - app-network
#     environment:
#       - DB_HOST=host.docker.internal  # Kết nối đến MySQL của Laragon
#       - DB_PORT=3306
#       - DB_DATABASE=product_db
#       - DB_USERNAME=root
#       - DB_PASSWORD=  # Trống vì Laragon không dùng password

#   nginx:
#     image: nginx:alpine
#     container_name: nginx
#     restart: unless-stopped
#     ports:
#       - "8000:80"
#     volumes:
#       - ./:/var/www
#       - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network
    environment:
      - DB_HOST=host.docker.internal  # Kết nối đến MySQL của Laragon
      - DB_PORT=3306
      - DB_DATABASE=product_db
      - DB_USERNAME=root
      - DB_PASSWORD=  # Trống vì Laragon không dùng password
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: